Update scrape.yaml

diff --git a/.github/workflows/scrape.yaml b/.github/workflows/scrape.yaml
--- a/.github/workflows/scrape.yaml
+++ b/.github/workflows/scrape.yaml
@@ -42,7 +42,12 @@ jobs:
       - name: 🛠 Install dependencies
         run: |
           touch Pipfile
+          pipenv --clear
           pipenv install --deploy --dev
+      
+      - name: 🛠 Check virtualenv path
+        run: |
+          pipenv --venv || echo "Virtual environment not found!"
 
       - name: 🕵️‍♂️ Scrape content and output
         run: |
